services:
  nats:
    container_name: ficlib_nats
    image: nats:latest
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    networks: ["ficlib_nats"]

  prometheus:
    container_name: ficlib_prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./apps/prometheus/config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=20d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks: ["ficlib_nats"]

  node_exporter:
    container_name: ficlib_node-exporter
    restart: always
    image: prom/node-exporter:latest
    ports:
      - '9101:9100'
    networks: ["ficlib_nats"]

  jaeger:
    container_name: ficlib_jaeger
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks: ["ficlib_nats"]

  grafana:
    container_name: ficlib_grafana
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: ["ficlib_nats"]

networks:
  ficlib_nats:
    name: ficlib_nats
    driver: bridge